### ISSUE TITLE
bug: 画面回転で強制終了する

### ISSUE THREAD

**Issue by NewNotMoon** [JAG-SC/ABC2016SpringCommunication#9]
画面を回転させると｢問題が発生したため、ーを終了します｣と表示され落ちる。
木村くんが復活したら治す。

**Comment by prprhyt** [comment]
Androidでは特に変更を加えない限り、画面の回転時に画面を再構成する。
デバッガで追ってみたところonDestroy内のbluetoothTask.doClose();を呼んだ直後に異常終了しているようだ。対処としては、回転時にonDestroyが呼ばれないようにするか、画面の向きを固定することが考えられる

**Comment by NewNotMoon** [comment]
向き固定は実装は楽だけど臭い物に蓋をする方法だからな…
回転時に通信タスクを再構成する必要はないはずだから、通信タスクは継続して実行するように変更したら治る？

**Comment by NewNotMoon** [comment]
アプリ一覧を開くだけで通信が最初からやり直しになるのはゲームとしてはまずいのでそちらも含めて修正すべきかと

**Comment by prprhyt** [comment]
回転対応をするならば再構成の対策を取らないとビューの情報もリセットされることがあるので、クライアントチームの負担も考えると縦か、横かで固定でいいかと思っています。どのみちハンドヘルドは置きっぱなしなら固定でいいような気がしますが

**Comment by NewNotMoon** [comment]
まあ、固定でもいいか。今回のアプリでは。
固定にしちゃいましょう。

**Comment by NewNotMoon** [comment]
いずれにせよアプリ一覧開いたり回転したりするたびにリセットされると面倒なのでどのみちその辺は修正すべきなはず

**Comment by prprhyt** [comment]
とりあえず、縦に固定しました。プルリク出してあります。
現在、クライアントチームに縦/横どちらの向きを正式採用するか問い合わせています。

**Comment by prprhyt** [comment]
申告が遅れました。縦を正式採用します
